### ISSUE TITLE
названия переменных

### ISSUE THREAD

**Issue by dasmike** [Boronus/Life#3]
имена переменных сбивают с толку что происходит в коде. 
например вот тут.
`for (let ip = i - 1; ip <= i + 1; ip++) {
            for (let jp = j - 1; jp <= j + 1; jp++) {
                if (i != ip || j != jp) {
                    //Зацикливаем процедуру на границе карты
                    let ipc = ip;
                    let jpc = jp;
                    if (ip === -1)
                        ipc = this.n - 1;
                    if (jp === -1)
                        jpc = this.n - 1;
                    if (ip === this.n)
                        ipc = 0;
                    if (jp === this.n)
                        jpc = 0;
                    //Считаем количество клеток
                    if (this.tableB[ipc][jpc] == 1)
                        col++;
                }
            }`
не стесняйся использовать имена подлиннее, код будет понятнее, имя будет говорить о предназначении переменной. Даже комментарии не везде нужны будут

**Comment by dasmike** [comment]
кстати, зачем тут дублируется строка "let ipc = ip;"?

**Comment by Boronus** [comment]
Там в одном случае i, в другом j. Переменные ipc и jpc ввел, поскольку они могут поменять свое значение на границе канваса, но ip и jp должны оставаться нетронутыми.

**Comment by Boronus** [comment]
Сменил 
    ip на line,
    jp на column,
    ipc на lineBorderLooped,
    jpc на columnBorderLooped.
Тоже не очень удачные названия, но ничего лучше не пришло в голову(
