### ISSUE TITLE
вынести селекторы

### ISSUE THREAD

**Issue by dasmike** [Boronus/Life#5]
много копий $(".js-life_screen") во view.js
вынеси поиск этого элемента в начало конструктора сохранив в какую то переменную. и заюзай ее в других местах. кстати, ты так и сделал это, сохранил этот элемент, но уже после того как заюзал $(".js-life_screen") в обработчиках. 
`$(".js-start_button").on("click", function(){
            $(".js-life_screen").css("background-color", "lightgreen");
            let $event = jQuery.Event("start");
            $('body').trigger($event);
        });
        $(".js-stop_button").on("click", function(){
            $(".js-life_screen").css("background-color", "lightblue");
            let $event = jQuery.Event("stop");
            $('body').trigger($event);
        });`
а потом сделал `let $screen =$(".js-life_screen");`
лучше наоборот.
`let $screen =$(".js-life_screen");
$(".js-start_button").on("click", function(){
            $screen.css("background-color", "lightgreen");
            let $event = jQuery.Event("start");
            $('body').trigger($event);
        });
        $(".js-stop_button").on("click", function(){
            $screen.css("background-color", "lightblue");
            let $event = jQuery.Event("stop");
            $('body').trigger($event);
        });
а лучше вообще все селекторы body, screen и кнопки вынеси в начало конструктора, сохранив их в константы =)

`

**Comment by dasmike** [comment]
стайлгайд от AirBnB : 2.1 Use const for all of your references; avoid using var. eslint: prefer-const, no-const-assign

**Comment by Boronus** [comment]
Вынес в файле view.js:
        const $screen = $('.js-life_screen');
        const $start_button = $('.js-start_button');
        const $stop_button = $('.js-stop_button');
        const $clear_button = $('.js-clear_button');
и в файле model.js:
        const $body = $('body');
